extract:
  src.news.news_data_extractor:
    news: NewsExtractor
  src.tedtalk.tedtalk_data_extractor:
    tedtalk: TedtalkExtractor

transform:
  src.news.news_data_transformer:
    news: NewsTransformer
  src.tedtalk.tedtalk_data_transformer:
    tedtalk: TedtalkTransformer

load:
  src.news.news_data_loader:
    news: NewsLoader
  src.tedtalk.tedtalk_data_loader:
    tedtalk: TedtalkLoader