elasticsearch:
  host: "http://127.0.0.1:9200"
  username: ""
  password: ""
  op_type: "index"
  index_name:
    news: cnn_t1
    tedtalk: tedtalk_t1

youtube:
  api_base_url: "https://www.googleapis.com/youtube/v3"
  api_key: "AIzaSyDxLknOj3nYnOjKs0Uc83omWXwNH6_TdHI"
