elasticsearch:
  op_type: "index"
  index_name:
    news: cnn
    tedtalk: tedtalk
    houzz: houzz

torch:
  pretrain_path: "paraphrase-multilingual-MiniLM-L12-v2"
  model_path: "./model/sentence_embedding_model.pth"

tedtalk:
  base_url: "https://www.ted.com"

youtube:
  api_base_url: "https://www.googleapis.com/youtube/v3"

houzz: 
  story_base_url: "https://www.houzz.com/ideabooks/p/"